name: go
on: [push]
jobs:
  build:
    name:build
    runs-on: unbuntu-latest
    env:
      CGO_ENABLED:1
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: build
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build  --tags "linux" -o ./compressImg ./cmd/main.go
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          # Artifact name
          name: artifact # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./compressImg
          # The desired behavior if no files are found using the provided path.
        Available Options:
          warn: Output a warning but do not fail the action
          error: Fail the action with an error message
          ignore: Do not output any warnings or errors, the action does not fail



